name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        django-version: ['3.2', '4.2', '5.0']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade Pip
        run: pip install -U pip
      - name: Install six
        run: pip install six
      - name: Install Django
        run: pip install Django==${{ matrix.django-version }}
      - name: Test
        run: python test_manage.py test
